# Site settings
title: Github Hall Of Fame
email: mehul.kar@gmail.com
description: Sometimes Github is awesome
baseurl: "/github-hall-of-fame"
twitter_username: mehulkar
github_username:  mehulkar

# Build settings
markdown: kramdown